### ISSUE TITLE
Using this with apollo-passport-local

### ISSUE THREAD

**Issue by GiladShoham** [apollo-passport/apollo-passport#12]
HI,
I saw that apollo-passport-local has a peer dependency with "apollo-passport": "^0.0.2".
When i try to install apollo-passport 0.0.7 i got an error:  UNMET PEER DEPENDENCY apollo-passport@0.0.7.
Is there any reason to use 0.0.2 specifically?
Will it work fine with 0.0.7?

Thanks.

**Comment by gadicc** [comment]
Hey Gilad, 0.0.7 is fine.  Note that work on the project is stalled and migrated to js-accounts, although I'm super behind on my contributions there :(

**Comment by GiladShoham** [comment]
Hi,
Thanks for the quick response.
Maybe it's worth just update the package.json of local and release new npm version?

I know you are in transition to js-accounts.
I really looking forward to this to be ready to use.
Meantime I start using this.
Hopefully, the transition from this to js-accounts will be easy.

I have some other question meantime, but I'll open separate issues.
